### ISSUE TITLE
项目缺少AES和DES文件

### ISSUE THREAD

**Issue by LJYes** [MxABC/DevDataTool#1]
如图：
![jietu](https://user-images.githubusercontent.com/18663185/34087066-b6a83248-e3db-11e7-94ef-94e9e2c08ef9.png)

**Comment by MxABC** [comment]
编译能通过吧，应该是空文件夹吧，记得是调用系统的AES和DES方法

**Comment by LJYes** [comment]
是的，编译可以通过，但是DES功能不能用，会报错。
如图：

![image](https://user-images.githubusercontent.com/18663185/34096786-9dc29256-e411-11e7-965f-12aa86abda21.png)
![Uploading image.png…]()

**Comment by MxABC** [comment]
这个是因为没有选补位类型，然后给的原始数据又不是分组的倍数导致的，后面代码加上数据异常处理

**Comment by MxABC** [comment]
你这个界面里面paddingtype 选一个类型，或者待加密数据字节数是8倍的倍数即可

**Comment by MxABC** [comment]
已修改
